WIP: watcherEx
node-casbin/redis-watcher pull request #27
Opened 2022-08-16 14:39 UTC by Shivansh-yadav13

- discussed with @nodece 
- I have created this to get reviews from everyone

2022-08-16 14:41 UTC, hsluoyz requested changes

2022-08-16 14:41 UTC, hsluoyz commented on src/watcherEx.ts
> +import { RedisClusterConnection, RedisConnection, RedisClient } from './redis';
apache header

2022-08-16 14:41 UTC, hsluoyz commented on src/watcherEx.ts
> +export interface WatcherExOptions extends RedisOptions {
test?

2022-08-16 15:43 UTC, hsluoyz commented
@Shivansh-yadav13 finish this: https://github.com/node-casbin/redis-watcher/issues/28 first

2022-08-17 14:16 UTC, nodece commented on src/watcherEx.ts
> +      if (msg.type === 'updateForAddPolicy' && watcherEx.callbackForAddPolicy) watcherEx.callbackForAddPolicy();
Could you make these types to a const or enum to avoid hard-code?

2022-08-17 14:17 UTC, nodece requested changes
There is nothing wrong with this PR overall, could you add a test for watcherEx?

2022-08-17 14:55 UTC, hsluoyz commented
@Shivansh-yadav13 fix errors:

![image](https://user-images.githubusercontent.com/3787410/185172171-3b6684cc-39e6-4398-aa7e-33bd26583d55.png)

2022-08-21 11:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/node-casbin/redis-watcher?pullRequest=27) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/node-casbin/redis-watcher?pullRequest=27) before we can accept your contribution.<br/>**4** out of **6** committers have signed the CLA.<br/><br/>:white_check_mark: nodece<br/>:white_check_mark: Shivansh-yadav13<br/>:white_check_mark: Zxilly<br/>:white_check_mark: hsluoyz<br/>:x: dependabot[bot]<br/>:x: semantic-release-bot<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/node-casbin/redis-watcher?pullRequest=27) it.</sub>

2022-08-21 11:51 UTC, hsluoyz commented
@Shivansh-yadav13 plz fix commits, they are messed up

![image](https://user-images.githubusercontent.com/3787410/185789551-c0b7491e-e3f1-4a0c-a6be-743d82c8a98d.png)

2022-08-22 09:09 UTC, merged

2022-08-22 09:20 UTC, Shivansh-yadav13 commented
I'm sorry rebasing accidentally caused this, I'll make fresh PR

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable

2022-08-22 09:21 UTC, Shivansh-yadav13 commented
I'm sorry rebasing accidentally caused this, I'll make fresh PR